name: Build
on:
  push:
    branches: [ main ]
    push_request:
jobs:
  build:
    run-on: ubuntu-latest
  steps:
    # Check out current repository
    - name: Fetch Sources
        uses: actions/checkout@v3.0.0

    # Validate wrapper
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1.0.4

    # Setup Java 11 environment for the next steps
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
        cache: gradle
    # Run tests
    - name: Run Tests
      run: ./gradlew test